- name: Sample Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: Create FlexVol
      na_ontap_volume:
        state: present
        type: dp
        name: "{{ destination_netapp_volume1_name }}"
        is_infinite: False
        aggregate_name: "{{ destination_netapp_data_aggregate_1 }}"
        size: "{{ destination_netapp_data_volume_size_tb }}"
        size_unit: tb
        space_guarantee: none
        policy: default
        percent_snapshot_space: 60
        vserver: "{{ destination_netapp_vserver_name }}"
        wait_for_completion: True
        hostname: "{{ destination_netapp_vserver_name }}"
        username: "{{ destination_netapp_vserver_username }}"
        password: "{{ destination_netapp_vserver_password }}"
    - name: Create SnapMirror
      na_ontap_snapmirror:
        state: present
        hostname: "{{ destination_netapp_vserver_name }}"
        username: "{{ destination_netapp_vserver_username }}"
        password: "{{ destination_netapp_vserver_password }}"
        source_vserver:  "{{ source_netapp_vserver_name }}"
        destination_vserver: "{{ destination_netapp_vserver_name }}"
        source_volume: "{{ source_netapp_volume1_name }}"
        destination_volume: "{{ destination_netapp_volume1_name }}"
