- name: Sample Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    login: &login
      hostname: "{{ source_netapp_cluster_name }}"
      username: "{{ source_netapp_cluster_username }}"
      password: "{{ source_netapp_cluster_password }}"
  tasks:
    - name: Create FlexVol 
      na_ontap_volume:
        state: present
        type: rw
        name: "{{ source_netapp_volume1_name }}"
        is_infinite: False
        aggregate_name: "{{ source_netapp_data_aggregate_1 }}"
        size: "{{ source_netapp_data_volume_size_tb }}"
        size_unit: tb
        space_guarantee: none
        policy: default
        percent_snapshot_space: 60
        vserver: "{{ source_netapp_vserver_name }}"
        <<: *login
