- name: Sample Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    login: &login
    - env_variables.yaml
  tasks:
    - name: create SnapShot
      na_ontap_snapshot:
        state: present
   #     hostname: "{{ source_netapp_vserver_name }}"
   #     username: "{{ source_netapp_vserver_username }}"
   #     password: "{{ source_netapp_vserver_password }}"
        vserver: "{{ source_netapp_vserver_name }}"
        volume: "{{ source_netapp_volume1_name }}"
        snapshot: "{{ source_netapp_volume1_snap_name }}"
        <<: *login
