- name: Sample Playbook
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: Delete SnapShot
      na_ontap_snapshot:
        state: absent
        hostname: "{{ source_netapp_vserver_name }}"
        username: "{{ source_netapp_vserver_username }}"
        password: "{{ source_netapp_vserver_password }}"
        vserver: "{{ source_netapp_vserver_name }}"
        volume: "{{ source_netapp_volume1_name }}"
        snapshot: "{{ source_netapp_volume1_snap_name }}"
